/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as ReservationIdIndexRouteImport } from './routes/$reservationId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIdIndexRoute = ReservationIdIndexRouteImport.update({
  id: '/$reservationId/',
  path: '/$reservationId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$reservationId': typeof ReservationIdIndexRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$reservationId': typeof ReservationIdIndexRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$reservationId/': typeof ReservationIdIndexRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$reservationId' | '/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$reservationId' | '/create'
  id: '__root__' | '/' | '/$reservationId/' | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReservationIdIndexRoute: typeof ReservationIdIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$reservationId/': {
      id: '/$reservationId/'
      path: '/$reservationId'
      fullPath: '/$reservationId'
      preLoaderRoute: typeof ReservationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReservationIdIndexRoute: ReservationIdIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
